//
//  UIKitSpikeData.swift
//  App
//
//  Created by Remi Robert on 14/09/2017.
//  Copyright © 2017 Remi Robert. All rights reserved.
//

import UIKit
import Domain

class UIKitSpikeData {
    static let datas: [Post] = [
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath 🥝"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen. 🥝"),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series. 🥝"),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in Also, go ahead and tune that for each device you’re supporting. K, thanks. 🥝"),
//        PostImage(images: [UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!], descriptionPost: "Also, go ahead and tune that for each device you’re supporting"),
//        PostImage(images: [UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!], descriptionPost: "Also, go ahead and tune that for each device you’re supporting"),
//        PostImage(images: [UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!], descriptionPost: "Also, go ahead and tune that for each device you’re supporting"),
        PostText(text: "Remember how I told you to to keep that 🥝"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external 🥝"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath 🥝"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen. 🥝"),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series. 🥝"),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks. 🥝"),
        PostText(text: "Remember how I told you to to keep that 🥝"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external 🥝"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath 🥝"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen. 🥝"),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series. 🥝"),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks. 🥝"),
        PostText(text: "Remember how I told you to to keep that 🥝"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external 🥝"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
        PostText(text: "Remember how I told you to to keep that"),
        PostText(text: "Usually the furthest range out from being visible. This is when content for each subnode in a cell, such as an ASNetworkImageNode, should be loaded from some external"),
        PostText(text: "ASTableDelegate lacks -tableView:heightForRowAtIndexPath"),
        PostText(text: "static height, you can optionally define a minimum and maximum size for your cells. In this case, you want each cell to at least be as tall as 2/3rds of the screen."),
        PostText(text: "Don’t worry about this too much right now; it’s covered in detail in part two of this series."),
        PostText(text: "And this gets quite a lot more complex when you factor in multiple dimensions of content. Do you have a page view controller with a collection view inside of each of the view controllers? Now you need to think of how you’re going to dynamically load content in both directions… Also, go ahead and tune that for each device you’re supporting. K, thanks."),
//        PostImage(images: [UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!, UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!, UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!, UIImagePNGRepresentation(#imageLiteral(resourceName: "image"))!], descriptionPost: "Also, go ahead and tune that for each device you’re supporting")
    ]
}
